name: grallcd
author: grallcd
url: https://grallcd.github.io
baseurl: /
resume_site: https://grallcd.github.io
description: grallcd's homepage
github_username: grallcd
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : grallcd.github.io
    owner : grallcd
    admin : grallcd
